"use client";

import { createSlice, PayloadAction } from "@reduxjs/toolkit";

export interface ContactDetailsType {
  id: number;
  firstName: string;
  lastName: string;
  status: boolean | null;
}

// Defining the state interface for contact details management
interface ContactDetailsState {
  contactDetailList: ContactDetailsType[]
  nextId: number  // Keeps track of the next ID to assign for a new contact
  editContactDetails : ContactDetailsType | null
}

// Initial state for the contact details slice
const initialState: ContactDetailsState = {
  contactDetailList: [],
  nextId: 1,
  editContactDetails : null
};

// Creating the contact details slice using Redux Toolkit's createSlice
const contactDetailsSlice = createSlice({
  name: "contactDetails", // Name of the slice
  initialState, // Initial state for the slice
  reducers: {
    // Reducer to add a new contact to the list
    setContactDetailList: (state, action: PayloadAction<Omit<ContactDetailsType, "id">>) => {
      const newContact = { ...action.payload, id: state.nextId }
      state.contactDetailList.push(newContact)
      state.nextId += 1 // Increment the next ID for future contacts
    },

    // Reducer to set the contact details for editing
    setEditContactDetails: (state, action: PayloadAction<number>) => {
      const contactToEdit = state.contactDetailList.find(contact => contact.id === action.payload);
      state.editContactDetails = contactToEdit || null;
    },

    // Reducer to edit an existing contact
    editContact: (state, action: PayloadAction<ContactDetailsType>) => {
      const index = state.contactDetailList.findIndex(contact => contact.id === action.payload.id);
      if (index !== -1) {
        state.contactDetailList[index] = action.payload;
      }
      state.editContactDetails = null
    },

     // Reducer to delete a contact from the list
    deleteContact: (state, action: PayloadAction<number>) => {
      state.contactDetailList = state.contactDetailList.filter(contact => contact.id !== action.payload);
    }
  },
});

// Exporting the action creators generated by createSlice
export const { setContactDetailList, setEditContactDetails, editContact, deleteContact } = contactDetailsSlice.actions;
export default contactDetailsSlice.reducer;
